"use client"  
import type { Metadata } from "next";
import "./globals.css";
import { useState } from 'react';
import Menu from "./components/Menu";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
    if (isMenuOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "auto";
    }
  };

  return (
    <html lang="en">
      <body className={`dark`}>
        <Menu isOpen={isMenuOpen} toggleMenu={toggleMenu} />
        <div className={isMenuOpen ? 'blur-sm pointer-events-none' : ''}>
          {children}
        </div>
      </body>
    </html>
  );
}
